install.packages("nlopt", repos='http://cran.us.r-project.org')
install.packages("tidyverse", repos='http://cran.us.r-project.org')
install.packages('devtools', repos='http://cran.us.r-project.org')
devtools::install_github('IRkernel/IRkernel')
IRkernel::installspec() 
